rpc_secret_key="769af463a39f077a0340a189e9c1ec28"
#连接超时时间，毫秒。
time_out=1000
[endpoint.user]
uri="tcp://172.20.4.19:9999" 
user =""
secret =""
compressor ="GZ"
[endpoint.product]
uri="tcp://172.20.4.19:9999" 
user =""
secret =""
compressor ="GZ"