rpc_secret_key="769af463a39f077a0340a189e9c1ec28"
#连接超时时间，毫秒。
time_out=2000
#测试线程数
threadnum=10
#测试时间 秒
test_time=30
[endpoint.dev]
uri="tcp://127.0.0.1:9999" 
user =""
secret =""
compressor =""
[endpoint.prod]
uri="tcp://127.0.0.1:9999" 
user =""
secret =""
compressor =""