rpc_secret_key="769af463a39f077a0340a189e9c1ec28"
#连接超时时间，毫秒。
time_out=2000
#测试线程数
threadnum=10
#测试时间 秒
test_time=10
[endpoint.dev]
uri="tcp://stdispatcher-acs.jumei.com:4041" 
user =""
secret =""
compressor =""
[endpoint.prod]
uri="tcp://dispatcher-acs.jumei.com:4040" 
user =""
secret =""
compressor =""