#rpc的名称,在同一个集群数据中心名字保持唯一
service_name = "myservice"
#net_type: tcp ,tcp4,tcp6
net_type = "tcp"
#端口
port = ":9999"
#最大连接数
max_connection=50
secret_key = "769af463a39f077a0340a189e9c1ec28"
# 日志文件地址，默认为程序同目录
log_file_path  = "./logs/"
# 日志记录类型：trace,debug,info,warn,error,critical
log_levels  = "debug,warn,error,critical"
